-- COLABORADORES ADMITIDOS

DECLARE @DATA VARCHAR(8);
SET @DATA = '201902%'

 SELECT * FROM (
-- SINAF SEGUROS 10
SELECT '10' COD_EMPRESA, 'SINAF SEGUROS' AS EMPRESA, RA_CATFUNC, RA_MAT, RA_NOMECMP, RA_ADMISSA, RA_DEMISSA, RE_DATA, RE_MATD, RE_MATP, RE_EMPD, RE_EMPP
FROM SRA100 SRA 
	LEFT JOIN SRE010 SRE ON RE_MATP = RA_MAT AND SRE.D_E_L_E_T_ = '' AND RE_EMPD <> RE_EMPP AND RE_EMPP = '10' AND RE_FILIALP = '01'
WHERE SRA.D_E_L_E_T_ = '' 
GROUP BY RA_CATFUNC, RA_MAT, RA_NOMECMP, RA_ADMISSA, RA_DEMISSA, RE_DATA, RE_MATD, RE_MATP, RE_EMPD, RE_EMPP
UNION ALL
-- BOM PASTOR 06
SELECT '06' COD_EMPRESA, 'BOM PASTOR' AS EMPRESA, RA_CATFUNC, RA_MAT, RA_NOMECMP, RA_ADMISSA, RA_DEMISSA, RE_DATA, RE_MATD, RE_MATP, RE_EMPD, RE_EMPP
FROM SRA060 SRA 
	LEFT JOIN SRE010 SRE ON RE_MATP = RA_MAT AND SRE.D_E_L_E_T_ = '' AND RE_EMPD <> RE_EMPP AND RE_EMPP = '06' AND RE_FILIALP = '01'
WHERE SRA.D_E_L_E_T_ = '' 
GROUP BY RA_CATFUNC, RA_MAT, RA_NOMECMP, RA_ADMISSA, RA_DEMISSA, RE_DATA, RE_MATD, RE_MATP, RE_EMPD, RE_EMPP
UNION ALL
-- SINAF 24H 07
SELECT '07' COD_EMPRESA, 'SINAF 24H' AS EMPRESA, RA_CATFUNC, RA_MAT, RA_NOMECMP, RA_ADMISSA, RA_DEMISSA, RE_DATA, RE_MATD, RE_MATP, RE_EMPD, RE_EMPP
FROM SRA070 SRA 
	LEFT JOIN SRE010 SRE ON RE_MATP = RA_MAT AND SRE.D_E_L_E_T_ = '' AND RE_EMPD <> RE_EMPP AND RE_EMPP = '07' AND RE_FILIALP = '01'
WHERE SRA.D_E_L_E_T_ = '' 
GROUP BY RA_CATFUNC, RA_MAT, RA_NOMECMP, RA_ADMISSA, RA_DEMISSA, RE_DATA, RE_MATD, RE_MATP, RE_EMPD, RE_EMPP
UNION ALL
-- JARDIM DE MESQUITA 0102
SELECT '0102' COD_EMPRESA, 'UNI - JARDIM DE MESQUITA' AS EMPRESA, RA_CATFUNC, RA_MAT, RA_NOMECMP, RA_ADMISSA, RA_DEMISSA, RE_DATA, RE_MATD, RE_MATP, RE_EMPD, RE_EMPP
FROM SRA010 SRA 
	LEFT JOIN SRE010 SRE ON RE_MATP = RA_MAT AND SRE.D_E_L_E_T_ = '' AND RE_EMPD <> RE_EMPP AND RE_EMPP = '01' AND RE_FILIALP = '02' 
WHERE SRA.D_E_L_E_T_ = '' 
GROUP BY RA_CATFUNC, RA_MAT, RA_NOMECMP, RA_ADMISSA, RA_DEMISSA, RE_DATA, RE_MATD, RE_MATP, RE_EMPD, RE_EMPP
UNION ALL
-- SINAF ASSISTENCIAL 04
SELECT '04' COD_EMPRESA, 'SINAF ASSISTENCIAL' AS EMPRESA, RA_CATFUNC, RA_MAT, RA_NOMECMP, RA_ADMISSA, RA_DEMISSA, RE_DATA, RE_MATD, RE_MATP, RE_EMPD, RE_EMPP
FROM SRA040 SRA 
	LEFT JOIN SRE010 SRE ON RE_MATP = RA_MAT AND SRE.D_E_L_E_T_ = '' AND RE_EMPD <> RE_EMPP AND RE_EMPP = '04' AND RE_FILIALP = '01' 
WHERE SRA.D_E_L_E_T_ = '' 
GROUP BY RA_CATFUNC, RA_MAT, RA_NOMECMP, RA_ADMISSA, RA_DEMISSA, RE_DATA, RE_MATD, RE_MATP, RE_EMPD, RE_EMPP
UNION ALL
-- CAFE DO JARDIM 12
SELECT '12' COD_EMPRESA, 'CAFE DO JARDIM' AS EMPRESA, RA_CATFUNC, RA_MAT, RA_NOMECMP, RA_ADMISSA, RA_DEMISSA, RE_DATA, RE_MATD, RE_MATP, RE_EMPD, RE_EMPP
FROM SRA120 SRA 
	LEFT JOIN SRE010 SRE ON RE_MATP = RA_MAT AND SRE.D_E_L_E_T_ = '' AND RE_EMPD <> RE_EMPP AND RE_EMPP = '12' AND RE_FILIALP = '01' 
WHERE SRA.D_E_L_E_T_ = '' 
GROUP BY RA_CATFUNC, RA_MAT, RA_NOMECMP, RA_ADMISSA, RA_DEMISSA, RE_DATA, RE_MATD, RE_MATP, RE_EMPD, RE_EMPP
UNION ALL
-- SINAF FAMILIA 03
SELECT '12' COD_EMPRESA, 'CAFE DO JARDIM' AS EMPRESA, RA_CATFUNC, RA_MAT, RA_NOMECMP, RA_ADMISSA, RA_DEMISSA, RE_DATA, RE_MATD, RE_MATP, RE_EMPD, RE_EMPP
FROM SRA030 SRA 
	LEFT JOIN SRE010 SRE ON RE_MATP = RA_MAT AND SRE.D_E_L_E_T_ = '' AND RE_EMPD <> RE_EMPP AND RE_EMPP = '03' AND RE_FILIALP = '01' 
WHERE SRA.D_E_L_E_T_ = '' 	
GROUP BY RA_CATFUNC, RA_MAT, RA_NOMECMP, RA_ADMISSA, RA_DEMISSA, RE_DATA, RE_MATD, RE_MATP, RE_EMPD, RE_EMPP
) COLABORADORES_ADMITIDOS
WHERE 
	RA_ADMISSA LIKE @DATA OR RE_DATA LIKE @DATA	AND (RA_DEMISSA > @DATA OR RA_DEMISSA = '') -- FILTRAR PERIODO
ORDER BY COD_EMPRESA
