SELECT EMPRESA, RA_MAT, RA_NOMECMP, RA_NASC, SUBSTRING(RA_NASC,5,2) AS MES_ANIVERSARIO, RA_DESFUNC, CTT_DESC01 FROM(	
	select 'UNI' AS EMPRESA, RA_MAT, RA_NOMECMP, RA_SITFOLH, RA_NASC, RA_DESFUNC, CTT_DESC01 
	FROM SRA010 SRA
	INNER JOIN CTT010 CTT ON RA_CC = CTT_CUSTO AND CTT.D_E_L_E_T_ = '' 
	WHERE SRA.D_E_L_E_T_ = ' ' 
		AND RA_FILIAL = '01'
		AND RA_SITFOLH <> 'D'
	UNION ALL
	select 'UNI FILIAL' AS EMPRESA, RA_MAT, RA_NOMECMP, RA_SITFOLH, RA_NASC, RA_DESFUNC, CTT_DESC01 
	FROM SRA010 SRA
	INNER JOIN CTT010 CTT ON RA_CC = CTT_CUSTO AND CTT.D_E_L_E_T_ = '' AND CTT_FILIAL = '02'
	WHERE SRA.D_E_L_E_T_ = ' ' 
		AND RA_FILIAL = '02'
		AND RA_SITFOLH <> 'D'
	UNION ALL
	select 'SINAF FAMILIA' AS EMPRESA, RA_MAT, RA_NOMECMP, RA_SITFOLH, RA_NASC, RA_DESFUNC, CTT_DESC01 
	FROM SRA030 SRA
	INNER JOIN CTT030 CTT ON RA_CC = CTT_CUSTO AND CTT.D_E_L_E_T_ = '' 
	WHERE SRA.D_E_L_E_T_ = ' ' 
		AND RA_SITFOLH <> 'D'
	UNION ALL
	select 'SINAF ASSISTENCIAL' AS EMPRESA, RA_MAT, RA_NOMECMP, RA_SITFOLH, RA_NASC, RA_DESFUNC, CTT_DESC01 
	FROM SRA040 SRA
	INNER JOIN CTT040 CTT ON RA_CC = CTT_CUSTO AND CTT.D_E_L_E_T_ = '' 
	WHERE SRA.D_E_L_E_T_ = ' ' 
		AND RA_SITFOLH <> 'D'
	UNION ALL
	select 'JAVA' AS EMPRESA, RA_MAT, RA_NOMECMP, RA_SITFOLH, RA_NASC, RA_DESFUNC, CTT_DESC01 
	FROM SRA050 SRA
	INNER JOIN CTT050 CTT ON RA_CC = CTT_CUSTO AND CTT.D_E_L_E_T_ = '' 
	WHERE SRA.D_E_L_E_T_ = ' ' 
		AND RA_SITFOLH <> 'D'
	UNION ALL
	select 'BOM PASTOR' AS EMPRESA, RA_MAT, RA_NOMECMP, RA_SITFOLH, RA_NASC, RA_DESFUNC, CTT_DESC01 
	FROM SRA060 SRA
	INNER JOIN CTT060 CTT ON RA_CC = CTT_CUSTO AND CTT.D_E_L_E_T_ = '' 
	WHERE SRA.D_E_L_E_T_ = ' ' 
		AND RA_SITFOLH <> 'D'
	UNION ALL
	select 'MARAJO' AS EMPRESA, RA_MAT, RA_NOMECMP, RA_SITFOLH, RA_NASC, RA_DESFUNC, CTT_DESC01 
	FROM SRA070 SRA
	INNER JOIN CTT070 CTT ON RA_CC = CTT_CUSTO AND CTT.D_E_L_E_T_ = '' 
	WHERE SRA.D_E_L_E_T_ = ' ' 
		AND RA_SITFOLH <> 'D'
	UNION ALL
	select 'MEMORIAL' AS EMPRESA, RA_MAT, RA_NOMECMP, RA_SITFOLH, RA_NASC, RA_DESFUNC, CTT_DESC01 
	FROM SRA080 SRA
	INNER JOIN CTT080 CTT ON RA_CC = CTT_CUSTO AND CTT.D_E_L_E_T_ = '' 
	WHERE SRA.D_E_L_E_T_ = ' ' 
		AND RA_SITFOLH <> 'D'
	UNION ALL
	select 'VITAL LATINA' AS EMPRESA, RA_MAT, RA_NOMECMP, RA_SITFOLH, RA_NASC, RA_DESFUNC, CTT_DESC01 
	FROM SRA090 SRA
	INNER JOIN CTT090 CTT ON RA_CC = CTT_CUSTO AND CTT.D_E_L_E_T_ = '' 
	WHERE SRA.D_E_L_E_T_ = ' ' 
		AND RA_SITFOLH <> 'D'
	UNION ALL
	select 'SINAF PREVIDENCIAL' AS EMPRESA, RA_MAT, RA_NOMECMP, RA_SITFOLH, RA_NASC, RA_DESFUNC, CTT_DESC01 
	FROM SRA100 SRA
	INNER JOIN CTT100 CTT ON RA_CC = CTT_CUSTO AND CTT.D_E_L_E_T_ = '' 
	WHERE SRA.D_E_L_E_T_ = ' ' 
		AND RA_SITFOLH <> 'D'	
	UNION ALL
	select 'CAFE DO JARDIM' AS EMPRESA, RA_MAT, RA_NOMECMP, RA_SITFOLH, RA_NASC, RA_DESFUNC, CTT_DESC01 
	FROM SRA120 SRA
	INNER JOIN CTT120 CTT ON RA_CC = CTT_CUSTO AND CTT.D_E_L_E_T_ = '' 
	WHERE SRA.D_E_L_E_T_ = ' ' 
		AND RA_SITFOLH <> 'D'
	UNION ALL
	select 'PATER SEGUROS' AS EMPRESA, RA_MAT, RA_NOMECMP, RA_SITFOLH, RA_NASC, RA_DESFUNC, CTT_DESC01 
	FROM SRA130 SRA
	INNER JOIN CTT130 CTT ON RA_CC = CTT_CUSTO AND CTT.D_E_L_E_T_ = '' 
	WHERE SRA.D_E_L_E_T_ = ' ' 
		AND RA_SITFOLH <> 'D'
) FUNC
WHERE RA_SITFOLH <> 'D' 
AND SUBSTRING(RA_NASC,5,2) = '05' 
ORDER BY EMPRESA



