SELECT 'UNI',C.QB_DESCRIC, A.RA_MAT, A.RA_NOME, substring(B.R7_DATA,7,2)+'/'+substring(B.R7_DATA,5,2)+'/'+substring(B.R7_DATA,1,4) 
FROM SRA010 A, SR7010 B, --MUDAR EMPRESA
SQB000 C
WHERE A.RA_MAT = B.R7_MAT
AND A.RA_DEPTO = C.QB_DEPTO
AND A.RA_FILIAL = B.R7_FILIAL
and A.RA_SITFOLH <> 'D'
AND R7_TIPO = '006' 
AND R7_DATA LIKE '2017%'
AND A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND C.D_E_L_E_T_ = ''
UNION ALL
SELECT 'SINAF ASSISTENCIAL',C.QB_DESCRIC, A.RA_MAT, A.RA_NOME, substring(B.R7_DATA,7,2)+'/'+substring(B.R7_DATA,5,2)+'/'+substring(B.R7_DATA,1,4) 
FROM SRA040 A, SR7040 B, --MUDAR EMPRESA
SQB000 C
WHERE A.RA_MAT = B.R7_MAT
AND A.RA_DEPTO = C.QB_DEPTO
AND A.RA_FILIAL = B.R7_FILIAL
and A.RA_SITFOLH <> 'D'
AND R7_TIPO = '006' 
AND R7_DATA LIKE '2017%'
AND A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND C.D_E_L_E_T_ = ''
UNION ALL
SELECT 'BOM PASTOR',C.QB_DESCRIC, A.RA_MAT, A.RA_NOME, substring(B.R7_DATA,7,2)+'/'+substring(B.R7_DATA,5,2)+'/'+substring(B.R7_DATA,1,4) 
FROM SRA060 A, SR7060 B, --MUDAR EMPRESA
SQB000 C
WHERE A.RA_MAT = B.R7_MAT
AND A.RA_DEPTO = C.QB_DEPTO
AND A.RA_FILIAL = B.R7_FILIAL
and A.RA_SITFOLH <> 'D'
AND R7_TIPO = '006' 
AND R7_DATA LIKE '2017%'
AND A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND C.D_E_L_E_T_ = ''
UNION ALL
SELECT 'MARAJÓ',C.QB_DESCRIC, A.RA_MAT, A.RA_NOME, substring(B.R7_DATA,7,2)+'/'+substring(B.R7_DATA,5,2)+'/'+substring(B.R7_DATA,1,4) 
FROM SRA070 A, SR7070 B, --MUDAR EMPRESA
SQB000 C
WHERE A.RA_MAT = B.R7_MAT
AND A.RA_DEPTO = C.QB_DEPTO
AND A.RA_FILIAL = B.R7_FILIAL
and A.RA_SITFOLH <> 'D'
AND R7_TIPO = '006' 
AND R7_DATA LIKE '2017%'
AND A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND C.D_E_L_E_T_ = ''
UNION ALL
SELECT 'VITAL',C.QB_DESCRIC, A.RA_MAT, A.RA_NOME, substring(B.R7_DATA,7,2)+'/'+substring(B.R7_DATA,5,2)+'/'+substring(B.R7_DATA,1,4) 
FROM SRA090 A, SR7090 B, --MUDAR EMPRESA
SQB000 C
WHERE A.RA_MAT = B.R7_MAT
AND A.RA_DEPTO = C.QB_DEPTO
AND A.RA_FILIAL = B.R7_FILIAL
and A.RA_SITFOLH <> 'D'
AND R7_TIPO = '006' 
AND R7_DATA LIKE '2017%'
AND A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND C.D_E_L_E_T_ = ''
UNION ALL
SELECT 'PREVIDENCIAL',C.QB_DESCRIC, A.RA_MAT, A.RA_NOME, substring(B.R7_DATA,7,2)+'/'+substring(B.R7_DATA,5,2)+'/'+substring(B.R7_DATA,1,4) 
FROM SRA100 A, SR7100 B, --MUDAR EMPRESA
SQB000 C
WHERE A.RA_MAT = B.R7_MAT
AND A.RA_DEPTO = C.QB_DEPTO
AND A.RA_FILIAL = B.R7_FILIAL
and A.RA_SITFOLH <> 'D'
AND R7_TIPO = '006' 
AND R7_DATA LIKE '2017%'
AND A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND C.D_E_L_E_T_ = ''
UNION ALL
SELECT 'CAFE DO JARDIM',C.QB_DESCRIC, A.RA_MAT, A.RA_NOME, substring(B.R7_DATA,7,2)+'/'+substring(B.R7_DATA,5,2)+'/'+substring(B.R7_DATA,1,4) 
FROM SRA120 A, SR7120 B, --MUDAR EMPRESA
SQB000 C
WHERE A.RA_MAT = B.R7_MAT
AND A.RA_DEPTO = C.QB_DEPTO
AND A.RA_FILIAL = B.R7_FILIAL
and A.RA_SITFOLH <> 'D'
AND R7_TIPO = '006' 
AND R7_DATA LIKE '2017%'
AND A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND C.D_E_L_E_T_ = '' 
