SELECT 'Uni Matriz' AS EMPRESA, SRA.RA_MAT, SRA.RA_NOME, SRA.RA_ADMISSA, SRA.RA_DEMISSA, SRA.RA_CIC, SRA.RA_CATFUNC, RA_CODFUNC, RA_SITFOLH
FROM SRA010 SRA
WHERE SRA.D_E_L_E_T_ = '' AND RA_FILIAL = '01' AND RA_SITFOLH <> 'D' AND RA_CATFUNC IN ('P', 'M', 'E', 'H', 'C')
UNION ALL
SELECT 'Uni Filial' AS EMPRESA, SRA.RA_MAT, SRA.RA_NOME, SRA.RA_ADMISSA, SRA.RA_DEMISSA, SRA.RA_CIC, SRA.RA_CATFUNC, RA_CODFUNC, RA_SITFOLH
FROM SRA010 SRA
WHERE SRA.D_E_L_E_T_ = '' AND RA_FILIAL = '02' AND RA_SITFOLH <> 'D' AND RA_CATFUNC IN ('P', 'M', 'E', 'H', 'C')
UNION ALL
SELECT 'Sinaf Familia' AS EMPRESA, SRA.RA_MAT, SRA.RA_NOME, SRA.RA_ADMISSA, SRA.RA_DEMISSA, SRA.RA_CIC, SRA.RA_CATFUNC, RA_CODFUNC, RA_SITFOLH
FROM SRA030 SRA
WHERE SRA.D_E_L_E_T_ = '' AND RA_FILIAL = '01' AND RA_SITFOLH <> 'D' AND RA_CATFUNC IN ('P', 'M', 'E', 'H', 'C')
UNION ALL
SELECT 'Sinaf Assistencial' AS EMPRESA, SRA.RA_MAT, SRA.RA_NOME, SRA.RA_ADMISSA, SRA.RA_DEMISSA, SRA.RA_CIC, SRA.RA_CATFUNC, RA_CODFUNC, RA_SITFOLH
FROM SRA040 SRA
WHERE SRA.D_E_L_E_T_ = '' AND RA_FILIAL = '01' AND RA_SITFOLH <> 'D' AND RA_CATFUNC IN ('P', 'M', 'E', 'H', 'C')
UNION ALL
SELECT 'Java Participações' AS EMPRESA, SRA.RA_MAT, SRA.RA_NOME, SRA.RA_ADMISSA, SRA.RA_DEMISSA, SRA.RA_CIC, SRA.RA_CATFUNC, RA_CODFUNC, RA_SITFOLH
FROM SRA050 SRA
WHERE SRA.D_E_L_E_T_ = '' AND RA_FILIAL = '01' AND RA_SITFOLH <> 'D' AND RA_CATFUNC IN ('P', 'M', 'E', 'H', 'C')
UNION ALL
SELECT 'Bom Pastor' AS EMPRESA, SRA.RA_MAT, SRA.RA_NOME, SRA.RA_ADMISSA, SRA.RA_DEMISSA, SRA.RA_CIC, SRA.RA_CATFUNC, RA_CODFUNC, RA_SITFOLH
FROM SRA060 SRA
WHERE SRA.D_E_L_E_T_ = '' AND RA_FILIAL = '01' AND RA_SITFOLH <> 'D' AND RA_CATFUNC IN ('P', 'M', 'E', 'H', 'C')
UNION ALL
SELECT 'Sinaf 24H' AS EMPRESA, SRA.RA_MAT, SRA.RA_NOME, SRA.RA_ADMISSA, SRA.RA_DEMISSA, SRA.RA_CIC, SRA.RA_CATFUNC, RA_CODFUNC, RA_SITFOLH
FROM SRA070 SRA
WHERE SRA.D_E_L_E_T_ = '' AND RA_FILIAL = '01' AND RA_SITFOLH <> 'D' AND RA_CATFUNC IN ('P', 'M', 'E', 'H', 'C')
UNION ALL
SELECT 'Memorial' AS EMPRESA, SRA.RA_MAT, SRA.RA_NOME, SRA.RA_ADMISSA, SRA.RA_DEMISSA, SRA.RA_CIC, SRA.RA_CATFUNC, RA_CODFUNC, RA_SITFOLH
FROM SRA080 SRA
WHERE SRA.D_E_L_E_T_ = '' AND RA_FILIAL = '01' AND RA_SITFOLH <> 'D' AND RA_CATFUNC IN ('P', 'M', 'E', 'H', 'C')
UNION ALL
SELECT 'Vital Latina' AS EMPRESA, SRA.RA_MAT, SRA.RA_NOME, SRA.RA_ADMISSA, SRA.RA_DEMISSA, SRA.RA_CIC, SRA.RA_CATFUNC, RA_CODFUNC, RA_SITFOLH
FROM SRA090 SRA
WHERE SRA.D_E_L_E_T_ = '' AND RA_FILIAL = '01' AND RA_SITFOLH <> 'D' AND (RA_CATFUNC IN ('P', 'M', 'E', 'H', 'C') OR RA_CATFUNC = 'A' AND RA_CODFUNC = '1011')
UNION ALL
SELECT 'Previdencial' AS EMPRESA, SRA.RA_MAT, SRA.RA_NOME, SRA.RA_ADMISSA, SRA.RA_DEMISSA, SRA.RA_CIC, SRA.RA_CATFUNC, RA_CODFUNC, RA_SITFOLH
FROM SRA100 SRA
WHERE SRA.D_E_L_E_T_ = '' AND RA_FILIAL = '01' AND RA_SITFOLH <> 'D' AND RA_CATFUNC IN ('P', 'M', 'E', 'H', 'C')
UNION ALL
SELECT 'Café do Jardim' AS EMPRESA, SRA.RA_MAT, SRA.RA_NOME, SRA.RA_ADMISSA, SRA.RA_DEMISSA, SRA.RA_CIC, SRA.RA_CATFUNC, RA_CODFUNC, RA_SITFOLH
FROM SRA120 SRA
WHERE SRA.D_E_L_E_T_ = '' AND RA_FILIAL = '01' AND RA_SITFOLH <> 'D' AND RA_CATFUNC IN ('P', 'M', 'E', 'H', 'C')
UNION ALL
SELECT 'Pater Seguros' AS EMPRESA, SRA.RA_MAT, SRA.RA_NOME, SRA.RA_ADMISSA, SRA.RA_DEMISSA, SRA.RA_CIC, SRA.RA_CATFUNC, RA_CODFUNC, RA_SITFOLH
FROM SRA130 SRA
WHERE SRA.D_E_L_E_T_ = '' AND RA_FILIAL = '01' AND RA_SITFOLH <> 'D' AND RA_CATFUNC IN ('P', 'M', 'E', 'H', 'C')
