SELECT
SUBSTRING(RA_USERLGI, 3, 1)+SUBSTRING(RA_USERLGI, 7, 1)+
SUBSTRING(RA_USERLGI, 11,1)+SUBSTRING(RA_USERLGI, 15,1)+
SUBSTRING(RA_USERLGI, 2, 1)+SUBSTRING(RA_USERLGI, 6, 1)+
SUBSTRING(RA_USERLGI, 10,1)+SUBSTRING(RA_USERLGI, 14,1)+
SUBSTRING(RA_USERLGI, 1, 1)+SUBSTRING(RA_USERLGI, 5, 1)+
SUBSTRING(RA_USERLGI, 9, 1)+SUBSTRING(RA_USERLGI, 13,1)+
SUBSTRING(RA_USERLGI, 17,1)+SUBSTRING(RA_USERLGI, 4, 1)+
SUBSTRING(RA_USERLGI, 8, 1) Usuario_CRIAÇÃO
FROM SRA010
SELECT
SUBSTRING(RA_USERLGA, 3, 1)+SUBSTRING(RA_USERLGA, 7, 1)+
SUBSTRING(RA_USERLGA, 11,1)+SUBSTRING(RA_USERLGA, 15,1)+
SUBSTRING(RA_USERLGA, 2, 1)+SUBSTRING(RA_USERLGA, 6, 1)+
SUBSTRING(RA_USERLGA, 10,1)+SUBSTRING(RA_USERLGA, 14,1)+
SUBSTRING(RA_USERLGA, 1, 1)+SUBSTRING(RA_USERLGA, 5, 1)+
SUBSTRING(RA_USERLGA, 9, 1)+SUBSTRING(RA_USERLGA, 13,1)+
SUBSTRING(RA_USERLGA, 17,1)+SUBSTRING(RA_USERLGA, 4, 1)+
SUBSTRING(RA_USERLGA, 8, 1) Usuario_ALTERAÇÃO
FROM SRA010
