SELECT TABELAS.NAME, COLUNAS.NAME AS CAMPO, TIPOS.NAME AS TIPO_CAMPO, COLUNAS.LENGTH AS TAMANHO_CAMPO, COLUNAS.ISNULLABLE AS EH_NULO
FROM sysobjects AS TABELAS,syscolumns AS COLUNAS,systypes AS TIPOS
WHERE TABELAS.ID = COLUNAS.ID AND COLUNAS.USERTYPE = TIPOS.USERTYPE AND TABELAS.NAME = 'SRA100'
