SELECT RD_DATARQ, RA_MAT, RA_NOME, RA_CC, RD_PD, RV_DESC, RD_HORAS, RD_VALOR 
FROM SRD100 RD
	INNER JOIN SRA100 RA ON RA.D_E_L_E_T_ = '' AND RA.RA_FILIAL = RD.RD_FILIAL AND RA.RA_MAT = RD.RD_MAT
	INNER JOIN SRV100 RV ON RV.D_E_L_E_T_ = '' AND RV.RV_COD = RD.RD_PD
	INNER JOIN CTT100 CTT ON CTT.CTT_CUSTO = RD.RD_CC AND CTT.D_E_L_E_T_ = '' AND RA.RA_FILIAL = CTT.CTT_FILIAL
WHERE
	RD.D_E_L_E_T_='' AND
	RD.RD_PD IN ('')AND
	RD.RD_DATARQ BETWEEN '20170101' AND '20173001' AND
	CTT.CTT_CUSTO BETWEEN '00000000' AND '99999999'
