SELECT '" + cUser + "' USUARIO, RA_FILIAL, CC, COD, RV_DESC, SUM(ANTERIOR) ANTERIOR, SUM(ATUAL) ATUAL, CODFOL, RESCATUAL, RESCANT 
FROM ( SELECT RA_FILIAL, RT_CC CC, RT_DATACAL, RV_COD AS COD, RV_DESC, RV_CODFOL AS CODFOL, CT5_FILIAL, 
SUM(CASE Substring(SRT.RT_DATACAL,1,6) WHEN '201708' THEN RT_VALOR ELSE 0 END) AS ANTERIOR, 
SUM(CASE Substring(SRT.RT_DATACAL,1,6) WHEN '201709' THEN RT_VALOR ELSE 0 END) AS ATUAL,	
ISNULL((SELECT SUM(RR_VALOR) from SRR100 WHERE Substring(RR_DATA,1,6) = '201708' AND RR_PD = '650' AND D_E_L_E_T_ = '' AND RR_CC = SRT.RT_CC),0) RESCATUAL, 
ISNULL((SELECT SUM(RR_VALOR) from SRR100 WHERE Substring(RR_DATA,1,6) = '201709' AND RR_PD = '650' AND D_E_L_E_T_ = '' AND RR_CC = SRT.RT_CC),0) RESCANT	
FROM SRV100 SRV 
	LEFT JOIN CT5100 CT5 ON SRV.RV_LCTOP = CT5.CT5_LANPAD AND CT5.D_E_L_E_T_ = ' ' 
	INNER JOIN SRT100 SRT ON SRV.RV_COD = SRT.RT_VERBA 
	INNER JOIN SRA100 SRA ON SRA.RA_FILIAL = SRT.RT_FILIAL and SRA.RA_MAT = SRT.RT_MAT AND SRT.D_E_L_E_T_ = '' 
WHERE Substring(SRT.RT_DATACAL,1,6) BETWEEN '201708'  AND '201709' 
	AND SRV.RV_CODFOL IN ('0136','0137','0138','0267','0268','0270','0274','0276','0277','0275','0272','0273','0271') AND SRA.RA_FILIAL = '01'
GROUP BY RA_FILIAL, RT_CC, RT_DATACAL, RV_COD, RV_DESC, RV_CODFOL, CT5_FILIAL 
) AS PROVFERIAS 
GROUP BY RA_FILIAL, CC, COD, RV_DESC, CODFOL, RESCATUAL, RESCANT 
