/*
Query para verificar admitidos em um determinado periodo
*/

SELECT * FROM
(SELECT RA_NOME, RA_ADMISSA FROM SRA010 WHERE RA_FILIAL = '01'
UNION ALL 
SELECT RA_NOME, RA_ADMISSA FROM SRA010  WHERE RA_FILIAL = '02'
UNION ALL
SELECT RA_NOME, RA_ADMISSA FROM SRA030
UNION ALL
SELECT RA_NOME, RA_ADMISSA FROM SRA040
UNION ALL  
SELECT RA_NOME, RA_ADMISSA FROM SRA050
UNION ALL
SELECT RA_NOME, RA_ADMISSA FROM SRA060
UNION ALL
SELECT RA_NOME, RA_ADMISSA FROM SRA070
UNION ALL
SELECT RA_NOME, RA_ADMISSA FROM SRA080
UNION ALL
SELECT RA_NOME, RA_ADMISSA FROM SRA090
UNION ALL
SELECT RA_NOME, RA_ADMISSA FROM SRA100
UNION ALL
SELECT RA_NOME, RA_ADMISSA FROM SRA110
UNION ALL
SELECT RA_NOME, RA_ADMISSA FROM SRA120
UNION ALL
SELECT RA_NOME, RA_ADMISSA FROM SRA130
UNION ALL
SELECT RA_NOME, RA_ADMISSA FROM SRA140
UNION ALL
SELECT RA_NOME, RA_ADMISSA FROM SRA150
UNION ALL
SELECT RA_NOME, RA_ADMISSA FROM SRA160
UNION ALL
SELECT RA_NOME, RA_ADMISSA FROM SRA170
UNION ALL
SELECT RA_NOME, RA_ADMISSA FROM SRA180
) FUNC 
--INSERIR DATA DE ADMISSAO
WHERE RA_ADMISSA BETWEEN '20180301' AND '20180331'
ORDER BY RA_ADMISSA
