/*
RELATORIO FOLHA DE PAGAMENTO
*/

SELECT RA_MAT, RA_NOMECMP, RA_SALARIO, RA_CC, CTT_DESC01, RA_ADMISSA, RA_CATFUNC, RA_SITFOLH, RD_DATARQ, RD_PD, RV_DESC, RD_HORAS, RD_VALOR  
FROM SRD090 SRD
	INNER JOIN SRA090 SRA ON SRA.D_E_L_E_T_ = ' ' 
		AND SRD.RD_FILIAL = SRA.RA_FILIAL 
		AND SRD.RD_MAT = SRA.RA_MAT 
		AND ((RA_CODFUNC = '1011' AND RA_CATFUNC = 'A') 
		OR RA_CATFUNC IN ('C','E'))
	INNER JOIN SRV090 SRV ON SRV.D_E_L_E_T_ = ' ' 
		AND SRD.RD_PD = SRV.RV_COD
	INNER JOIN CTT090 CTT ON CTT.D_E_L_E_T_ = ' ' 
		AND CTT.CTT_CUSTO = SRA.RA_CC
WHERE SRD.D_E_L_E_T_ = ' ' 
ORDER BY RA_NOME, RD_DATARQ, RD_PD
