SELECT 'PREVIDENCIAL' AS EMPRESA, CT2.CT2_FILIAL, CT2.CT2_DATA, CT2.CT2_LOTE, CT2.CT2_SBLOTE,
	CASE CT2_DC 
	WHEN '1' THEN 'DEBITO'
	WHEN '2' THEN 'CREDITO' 
	WHEN '3' THEN 'PARTIDA DOBRADA'
	WHEN '4' THEN 'CONT. HIST'
	WHEN '5' THEN 'RATEIO'
	WHEN '6' THEN 'LANCAMENTO PADRAO' 
	END AS CT2_DC, 
	CT2.CT2_DEBITO, CT2.CT2_CREDIT, CT2.CT2_VALOR, CT2.CT2_HIST, CT2.CT2_CCD, CT2.CT2_CCC, CT2.CT2_CLVLDB, CT2.CT2_CLVLCR, CT2.CT2_ITEMC, 
	CT2.CT2_ITEMD, CT2_LOG.TTAT_USER, TTAT_USERID, 
	CASE TTAT_OPERATI
	WHEN 'U' THEN 'ALTERACAO'
	WHEN 'I' THEN 'INCLUSAO' 
	END AS TTAT_OPERATI,
	CONVERT(DATE,TTAT_DTIME,103) AS DATA_LOG,
	CONVERT(TIME,TTAT_DTIME,113) AS HORA_LOG
FROM CT2100 CT2
	INNER JOIN CT2100_TTAT_LOG CT2_LOG ON TTAT_RECNO = CT2.R_E_C_N_O_ 
		AND CT2_LOG.TTAT_OPERATI in ('I', 'U')
WHERE CT2.D_E_L_E_T_ = ''
	AND CT2_DATA BETWEEN '20180601' AND '20180630'
GROUP BY CT2_LOG.TTAT_USER, CT2.CT2_FILIAL, CT2.CT2_DATA, CT2.CT2_LOTE, CT2.CT2_SBLOTE, CT2_DC, CT2.CT2_DEBITO, CT2.CT2_CREDIT, CT2.CT2_VALOR, 
	CT2.CT2_HIST, CT2.CT2_CCD, CT2.CT2_CCC, CT2.CT2_CLVLDB, CT2.CT2_CLVLCR, CT2.CT2_ITEMC, 
	CT2.CT2_ITEMD, CT2_LOG.TTAT_USER, TTAT_USERID, TTAT_OPERATI, TTAT_DTIME, CT2_USERGI, TTAT_DTIME
ORDER BY CT2_DATA
