/*
RELATÓRIO ESPELHO DE REMUNERAÇÃO
AUTOR: YURI MARTINS
*/

SELECT SRA.RA_MAT, SRA.RA_NOME, SRA.RA_CATFUNC, SRA.RA_LOCAL,
	CASE substring(RA_LOCAL,9,30) 
		WHEN 'RIO BRANCO 23' THEN 'RB'
		WHEN 'RIO BRANCO 27' THEN 'RB'
		WHEN 'RIO BRANCO 28' THEN 'RB'
		WHEN 'RIO BRANCO 29' THEN 'RB'
		WHEN 'RIO BRANCO 35' THEN 'RB'
		WHEN 'ZONA NORTE' THEN 'ZN' 
		WHEN 'ZONA OESTE' THEN 'ZO'
		WHEN 'BAIXADA FLUMINENSE' THEN 'BF' 
		WHEN 'GRANDE NITEROI' THEN 'GN'	 
	ELSE '' END UNIDADE, 
	SRD.RD_PD, SRV.RV_DESC, 
	CASE SRV.RV_TIPOCOD 
		WHEN '1' THEN 'PROVENTO' 
		WHEN '2' THEN 'DESCONTO'
		WHEN '3' THEN 'BASE'
	END AS TIPO,	
	SRV.RV_TIPOCOD, SRD.RD_VALOR, SRD.RD_DATARQ, SRD.RD_PERIODO, SRD.RD_MES, SRD.RD_TIPO2
FROM SRD090 SRD 
	INNER JOIN SRA090 SRA ON SRA.RA_MAT = SRD.RD_MAT 
		AND SRA.RA_SITFOLH <> 'D' 
		AND SRA.RA_CATFUNC = 'C' --FILTRAR CATEGORIA
		AND SRA.D_E_L_E_T_ = ''
	INNER JOIN SRV090 SRV ON SRV.RV_COD = SRD.RD_PD 
		AND SRV.D_E_L_E_T_ = ''
WHERE SRD.RD_DATARQ LIKE '2016%' -- FILTRAR PERIODO
	AND SRD.RD_MAT = '001018' --FILTRAR MATRICULA
	--AND RD_PD IN ('698','799','179','180','126','108','137', '321', '507')
	AND SRD.RD_MES = '01' -- FILTRAR MES
	AND SRD.D_E_L_E_T_ = ''
ORDER BY SRD.RD_MES, SRV.RV_TIPOCOD

/*
RELATÓRIO ESPELHO DE REMUNERAÇÃO - QUERY 02 - COMPLEMENTO
*/

SELECT PROVENTO, DESCONTO, BASE, RD_MES FROM (
SELECT  RA_MAT, RV_TIPOCOD, SUM(PROVENTO) AS PROVENTO, SUM(DESCONTO) AS DESCONTO, SUM(BASE)	AS BASE, RD_MES
FROM ( 
SELECT 
	SRA.RA_MAT, 
	SRA.RA_NOME, 
	SRA.RA_CATFUNC, 
	SRA.RA_LOCAL,
	CASE substring(RA_LOCAL,9,30) 
		WHEN 'RIO BRANCO 23' THEN 'RB'
		WHEN 'RIO BRANCO 27' THEN 'RB'
		WHEN 'RIO BRANCO 28' THEN 'RB'
		WHEN 'RIO BRANCO 29' THEN 'RB'
		WHEN 'RIO BRANCO 35' THEN 'RB'
		WHEN 'ZONA NORTE' THEN 'ZN' 
		WHEN 'ZONA OESTE' THEN 'ZO'
		WHEN 'BAIXADA FLUMINENSE' THEN 'BF' 
		WHEN 'GRANDE NITEROI' THEN 'GN'	 
	ELSE '' END UNIDADE, 
	SRD.RD_PD, SRV.RV_DESC, 
	CASE SRV.RV_TIPOCOD 
		WHEN '1' THEN 'PROVENTO' 
		WHEN '2' THEN 'DESCONTO'
		WHEN '3' THEN 'BASE'
		WHEN '4' THEN 'BASE PARA DESCONTO'
	END AS TIPO,
	SUM(CASE RV_TIPOCOD WHEN '1' THEN RD_VALOR END) AS PROVENTO,
	SUM(CASE RV_TIPOCOD WHEN '2' THEN RD_VALOR END) AS DESCONTO,
	SUM(CASE RV_TIPOCOD WHEN '3' THEN RD_VALOR END) AS BASE,
	SUM(CASE RV_TIPOCOD WHEN '4' THEN RD_VALOR END) AS BASE_DESCONTO,
	SRV.RV_TIPOCOD, SRD.RD_VALOR, SRD.RD_DATARQ, SRD.RD_PERIODO, SRD.RD_MES, SRD.RD_TIPO2
FROM SRD090 SRD 
	INNER JOIN SRA090 SRA ON SRA.RA_MAT = SRD.RD_MAT 
		AND SRA.RA_SITFOLH <> 'D' 
		AND SRA.RA_CATFUNC = 'C' --FILTRAR CATEGORIA
		AND SRA.D_E_L_E_T_ = ''
	INNER JOIN SRV090 SRV ON SRV.RV_COD = SRD.RD_PD 
		AND SRV.D_E_L_E_T_ = ''
WHERE SRD.RD_DATARQ LIKE '2016%' -- FILTRAR PERIODO
	AND SRD.RD_MAT = '001018' --FILTRAR MATRICULA
	--AND RD_PD IN ('698','799','179','180','126','108','137', '321', '507')
	--AND SRD.RD_MES = '01' -- FILTRAR MES
	AND SRD.D_E_L_E_T_ = '' 
	GROUP BY RA_MAT, RA_NOME, RA_CATFUNC, RA_LOCAL, RD_PD, RV_DESC, RV_TIPOCOD, RD_VALOR, RD_DATARQ, RD_PERIODO, RD_MES, RD_TIPO2
	) TESTE
GROUP BY RA_MAT, RV_TIPOCOD, RD_MES ) TESTE2
--ORDER BY RD_MES
