--VERSAO 01
SELECT CASE substring(SRA.RA_LOCAL,9,30) 
	WHEN 'RIO BRANCO 23' THEN 'RB'
	WHEN 'RIO BRANCO 27' THEN 'RB'
	WHEN 'RIO BRANCO 28' THEN 'RB'
	WHEN 'RIO BRANCO 29' THEN 'RB'
	WHEN 'RIO BRANCO 35' THEN 'RB'
	WHEN 'ZONA NORTE' THEN 'ZN' 
	WHEN 'ZONA OESTE' THEN 'ZO'
	WHEN 'BAIXADA FLUMINENSE' THEN 'BF' 
	WHEN 'GRANDE NITEROI' THEN 'GN'	 
	ELSE '' 
	END UN, 	
	CTT.CTT_DESC01 AS DESCRICAO_CC, CTT.CTT_CUSTO, SRA.RA_MAT, SRA.RA_NOMECMP, SRA.RA_DESFUNC ,
	RA_ADMISSA, 
	RF_DATABAS,
	CONVERT(DATE,DateAdd(day, +1, SRF.RF_DATAFIM)) AS INICIO_PERIODO, 
	CONVERT(DATE,dateadd(year,+1,SRF.RF_DATAFIM)) AS RF_DATAFIM,
	CONVERT(DATE,DateAdd(year, +1, SRF.RF_DATABAS)) AS MES_COMPETENCIA, 
	CONVERT(DATE,DateAdd(day, +30, SRF.RF_DATAFIM)) AS DATA_IDEAL,
	CONVERT(DATE,DateAdd(day, +90, SRF.RF_DATAFIM)) AS DATA_LIMITE,  
	SRF.RF_DFERVAT, SRF.RF_DFALVAT, SRF.RF_DFERAAT, SRF.RF_DFALAAT,RF_DIASDIR, SRF.RF_DATAINI
FROM SRF090 SRF
	INNER JOIN SRA090 SRA ON SRA.RA_MAT = SRF.RF_MAT 
		AND SRA.D_E_L_E_T_ = '' 
		AND SRA.RA_CATFUNC IN ('C') -- INSERIR CATEGORIA DO COLABORADOR 
		AND SRA.RA_SITFOLH <> 'D' -- EXCLUIR DEMITIDOS
	INNER JOIN CTT090 CTT ON SRA.RA_CC = CTT.CTT_CUSTO 
		AND CTT.D_E_L_E_T_ = ''
		AND RF_STATUS = '1' -- FILTRANDO ATIVOS
WHERE SRF.D_E_L_E_T_ = '' 	
ORDER BY RA_NOMECMP

--VERSAO 02 

SELECT CASE substring(SRA.RA_LOCAL,9,30) 
	WHEN 'RIO BRANCO 23' THEN 'RB'
	WHEN 'RIO BRANCO 27' THEN 'RB'
	WHEN 'RIO BRANCO 28' THEN 'RB'
	WHEN 'RIO BRANCO 29' THEN 'RB'
	WHEN 'RIO BRANCO 35' THEN 'RB'
	WHEN 'ZONA NORTE' THEN 'ZN' 
	WHEN 'ZONA OESTE' THEN 'ZO'
	WHEN 'BAIXADA FLUMINENSE' THEN 'BF' 
	WHEN 'GRANDE NITEROI' THEN 'GN'	 
	ELSE '' 
	END UN, 	
	CTT.CTT_DESC01 AS DESCRICAO_CC, CTT.CTT_CUSTO, SRA.RA_MAT, SRA.RA_NOMECMP, SRA.RA_DESFUNC, SRA.RA_CATFUNC,
	SRA.RA_ADMISSA, 
	CONVERT(DATE,SRF.RF_DATABAS,103) RF_DATABAS, 
	CONVERT(DATE,SRF.RF_DATAFIM,103) RF_DATAFIM,
	--CONVERT(DATE,DateAdd(day, +1, SRF.RF_DATAFIM)) AS INICIO_PERIODO, 
	--CONVERT(DATE,dateadd(year,+1,SRF.RF_DATAFIM)) AS DATAFIM,
	--CONVERT(DATE,DateAdd(year, +1, SRF.RF_DATABAS)) AS MES_COMPETENCIA, 
	(SUBSTRING(RF_DATAFIM,5,2) + '/' + SUBSTRING(RF_DATAFIM,1,4)) AS MESANO,
	CONVERT(DATE,DateAdd(day, +30, SRF.RF_DATAFIM)) AS IDEAL,
		CONVERT(DATE,dateadd(day, -92, DateAdd(year, +1, SRF.RF_DATAFIM)))   AS LIMITE_IDEAL,
		DATEPART(DW,CONVERT(DATE,dateadd(day, -92, DateAdd(year, +1, SRF.RF_DATAFIM)))) DIASEMANA,
	--CONVERT(DATE,RF_DATAINI,103) AS DATA2,  
	RF_DATAINI,
	SRF.RF_DFERVAT, SRF.RF_DFALVAT, SRF.RF_DFERAAT, SRF.RF_DFALAAT,RF_DIASDIR, RF_STATUS
FROM SRF090 SRF
	INNER JOIN SRA090 SRA ON SRA.RA_MAT = SRF.RF_MAT 
		AND SRA.D_E_L_E_T_ = '' 
		--AND SRA.RA_CATFUNC IN ('C') -- INSERIR CATEGORIA DO COLABORADOR 
		AND SRA.RA_SITFOLH <> 'D' -- EXCLUIR COLABORADORES DEMITIDOS
	INNER JOIN CTT090 CTT ON SRA.RA_CC = CTT.CTT_CUSTO 
		AND CTT.D_E_L_E_T_ = ''
		AND RF_STATUS = '1' -- FILTRANDO COLAB C/ FERIAS ATIVAS (1-ATIVO / 2- PRESCRITO / 3-PAGO)
WHERE SRF.D_E_L_E_T_ = '' 	
ORDER BY RA_NOMECMP


--V03

/*
RELATORIO CONTROLE DE FERIAS DOS COLABORADORES
*/

SELECT DIA_IDEALMAX, IDEALMAX,
--LIMITE IDEAL MAXIMO
CASE DIA_IDEALMAX
	WHEN '1' THEN DateAdd(day, -3, IDEALMAX) --SE DOMINGO (DESCAMSO SEMANAL REMUNERADO) 72H ANTES
	WHEN '7' THEN DateAdd(day, -3, IDEALMAX) --SE SABADO (DESCAMSO SEMANAL REMUNERADO) 72H ANTES
	ELSE IDEALMAX
END AS IDEALMAX_NOVO, 
DIA_IDEAL, IDEAL,
--LIMITE IDEAL 
CASE DIA_IDEAL
	WHEN '1' THEN DateAdd(day, -3, IDEAL) --SE DOMINGO (DESCAMSO SEMANAL REMUNERADO) 72H ANTES
	WHEN '7' THEN DateAdd(day, -3, IDEAL) --SE SABADO (DESCAMSO SEMANAL REMUNERADO) 72H ANTES
	ELSE IDEAL
END AS IDEAL_NOVO,
* FROM
(SELECT CASE substring(SRA.RA_LOCAL,9,30) 
	WHEN 'RIO BRANCO 23' THEN 'RB'
	WHEN 'RIO BRANCO 27' THEN 'RB'
	WHEN 'RIO BRANCO 28' THEN 'RB'
	WHEN 'RIO BRANCO 29' THEN 'RB'
	WHEN 'RIO BRANCO 35' THEN 'RB'
	WHEN 'ZONA NORTE' THEN 'ZN' 
	WHEN 'ZONA OESTE' THEN 'ZO'
	WHEN 'BAIXADA FLUMINENSE' THEN 'BF' 
	WHEN 'GRANDE NITEROI' THEN 'GN'	 
	ELSE '' 
	END UN, 	
	CTT.CTT_DESC01 AS DESCRICAO_CC, CTT.CTT_CUSTO, SRA.RA_MAT, SRA.RA_NOMECMP, SRA.RA_DESFUNC, SRA.RA_CATFUNC,
	SRA.RA_ADMISSA, 
	CONVERT(DATE,SRF.RF_DATABAS,103) RF_DATABAS, 
	CONVERT(DATE,SRF.RF_DATAFIM,103) RF_DATAFIM,
	--CONVERT(DATE,DateAdd(day, +1, SRF.RF_DATAFIM)) AS INICIO_PERIODO, 
	--CONVERT(DATE,dateadd(year,+1,SRF.RF_DATAFIM)) AS DATAFIM,
	--CONVERT(DATE,DateAdd(year, +1, SRF.RF_DATABAS)) AS MES_COMPETENCIA, 
	(SUBSTRING(RF_DATAFIM,5,2) + '/' + SUBSTRING(RF_DATAFIM,1,4)) AS MESANO,
	CONVERT(DATE,DateAdd(day, +30, SRF.RF_DATAFIM)) AS IDEAL,
	CONVERT(DATE,dateadd(day, -92, DateAdd(year, +1, SRF.RF_DATAFIM)))   AS IDEALMAX,
	DATEPART(DW,CONVERT(DATE,dateadd(day, -92, DateAdd(year, +1, SRF.RF_DATAFIM)))) DIA_IDEALMAX,
	DATEPART(DW,CONVERT(DATE,dateadd(day, +30, DateAdd(year, +1, SRF.RF_DATAFIM)))) DIA_IDEAL,
	--CONVERT(DATE,RF_DATAINI,103) AS DATA2,  
	RF_DATAINI, SRF.RF_DFERVAT, SRF.RF_DFALVAT, SRF.RF_DFERAAT, SRF.RF_DFALAAT,RF_DIASDIR, RF_STATUS
FROM SRF090 SRF
	INNER JOIN SRA090 SRA ON SRA.RA_MAT = SRF.RF_MAT 
		AND SRA.D_E_L_E_T_ = '' 
		--AND SRA.RA_CATFUNC IN ('C') -- INSERIR CATEGORIA DO COLABORADOR 
		AND SRA.RA_SITFOLH <> 'D' -- EXCLUIR COLABORADORES DEMITIDOS
	INNER JOIN CTT090 CTT ON SRA.RA_CC = CTT.CTT_CUSTO 
		AND CTT.D_E_L_E_T_ = ''
		AND RF_STATUS = '1' -- FILTRANDO COLABORADORES C/ FERIAS ATIVAS (1-ATIVO / 2- PRESCRITO / 3-PAGO)
WHERE SRF.D_E_L_E_T_ = '' 	
) TESTE
ORDER BY RF_DATABAS


