/*

RELATÓRIO ESPELHO DE REMUNERAÇÃO
AUTOR: YURI MARTINS

*/

SELECT SRA.RA_MAT, SRA.RA_NOME, SRA.RA_CATFUNC, SRA.RA_LOCAL, SRD.RD_PD, SRV.RV_DESC, SRD.RD_VALOR, SRD.RD_DATARQ, SRD.RD_PERIODO, SRD.RD_MES, SRD.RD_TIPO2
FROM SRD090 SRD 
	INNER JOIN SRA090 SRA ON SRA.RA_MAT = SRD.RD_MAT 
		AND SRA.RA_SITFOLH <> 'D' 
		AND SRA.RA_CATFUNC = 'C' --FILTRAR CATEGORIA
		AND SRA.D_E_L_E_T_ = ''
	INNER JOIN SRV090 SRV ON SRV.RV_COD = SRD.RD_PD 
		AND SRV.D_E_L_E_T_ = ''
WHERE SRD.RD_DATARQ LIKE '2016%' -- FILTRAR PERIODO
	AND SRD.RD_MAT = '001018' --FILTRAR MATRICULA
	--AND RD_PD IN ('698','799','179','180','126','108','137', '321', '507')
	--AND SRD.RD_MES = '01'
	AND SRD.D_E_L_E_T_ = ''
ORDER BY SRD.RD_MES
