SELECT * FROM SRD100
SELECT * FROM SRV100
SELECT * FROM SRA100
SELECT * FROM SRG100

SELECT RV_COD, RV_DESC, RD_VALOR, RD_DATPGT, SUBSTRING(RCC_CONTEU,1,2) CODIGO FROM SRV090 SRV
	INNER JOIN SRD090 SRD ON SRD.RD_PD = SRV.RV_COD AND SRD.D_E_L_E_T_ = ''
	INNER JOIN SRG090 SRG ON SRG.RG_MAT = RD_MAT AND SRG.D_E_L_E_T_ = ''
	INNER JOIN RCC090 RCC ON SUBSTRING(RCC.RCC_CONTEU,1,2) = SRG.RG_TIPORES AND RCC.D_E_L_E_T_ = '' AND SUBSTRING(RCC.RCC_CONTEU,1,2) = '23'
	INNER JOIN SRA090 SRA ON SRA.RA_MAT = SRG.RG_MAT AND SRA.D_E_L_E_T_ = '' AND RA_CATFUNC = 'C'
WHERE RV_COD IN ('701', '702', '703', '825', '832') AND RD_DATPGT BETWEEN '2016' AND '2017' AND SRV.D_E_L_E_T_ = '' AND RV_COD = '701'

--PEGAR O CODIGO E DESCRICAO DA RESCISAO
SELECT SUBSTRING(RCC_CONTEU,1,2) CODIGO, SUBSTRING(RCC_CONTEU,3,30) DESCR FROM RCC090 RCC WHERE RCC_CODIGO = 'S043' AND RCC.D_E_L_E_T_ = ''

SELECT RA_MAT, RA_NOME, RA_ADMISSA, RA_DEMISSA, RA_DESFUNC, * FROM SRA090  WHERE RA_DEMISSA BETWEEN '2016' AND '2017' AND RA_CATFUNC = 'C'

--VERSAO 02 
SELECT RA_MAT, RA_NOME, RA_DEMISSA, RA_DESFUNC, SUBSTRING(RCC_CONTEU,1,2) AS CODIGO, SUBSTRING(RCC_CONTEU,3,30) AS DESCR, RD_PD, RD_VALOR
FROM SRA090 SRA
	INNER JOIN SRG090 SRG ON SRG.RG_MAT = RA_MAT 
		AND SRG.D_E_L_E_T_ = ''
	INNER JOIN RCC090 RCC ON SUBSTRING(RCC.RCC_CONTEU,1,2) = SRG.RG_TIPORES 
		AND RCC_CODIGO = 'S043'
		AND  SUBSTRING(RCC_CONTEU,1,2) = '20'
		AND RCC.D_E_L_E_T_ = ''
	INNER JOIN SRD090 SRD ON SRD.RD_MAT = SRA.RA_MAT
		AND SRD.D_E_L_E_T_ = ''	AND RD_TIPO2 = 'R'
	INNER JOIN SRV090 SRV ON SRV.RV_COD = SRD.RD_PD
		--AND RV_COD IN ('701','702','703','825','832')
		AND RV_COD = '701'
		AND SRV.D_E_L_E_T_ = '' 
WHERE RA_DEMISSA LIKE '2016%' 
	AND RA_CATFUNC = 'C'
	AND SRA.D_E_L_E_T_ = ''
GROUP BY RA_MAT, RA_NOME, RA_DEMISSA, RA_DESFUNC, RCC_CONTEU, RD_PD, RD_VALOR
ORDER BY RA_MAT


-- versao 03

SELECT RA_MAT, RA_NOME, RA_DEMISSA, RA_DESFUNC, SUBSTRING(RCC43.RCC_CONTEU,1,2) AS CODIGO, SUBSTRING(RCC43.RCC_CONTEU,3,30) AS DESCR, RD_PD, RD_VALOR, RA_TPCONTR,
SUBSTRING(RCC37.RCC_CONTEU,3,4) EMPRESA, SUBSTRING(RCC37.RCC_CONTEU,12,4) ACTRAB, SUBSTRING(RCC37.RCC_CONTEU,28,3) FGTS
FROM SRA090 SRA
	INNER JOIN SRG090 SRG ON SRG.RG_MAT = RA_MAT 
		AND SRG.D_E_L_E_T_ = ''
	INNER JOIN RCC090 RCC43 ON SUBSTRING(RCC43.RCC_CONTEU,1,2) = SRG.RG_TIPORES
		AND RCC_CODIGO = 'S043'
		AND RCC43.D_E_L_E_T_ = ''
	LEFT JOIN RCC090 RCC37 ON SUBSTRING(RCC37.RCC_CONTEU,1,1) = RA_TPCONTR
		AND RCC37.RCC_CODIGO = 'S037'
		AND RCC37.D_E_L_E_T_ = ''
	INNER JOIN SRD090 SRD ON SRD.RD_MAT = SRA.RA_MAT
		AND SRD.D_E_L_E_T_ = ''	AND RD_TIPO2 = 'R'
	INNER JOIN SRV090 SRV ON SRV.RV_COD = SRD.RD_PD
		AND RV_COD IN ('701','702','703','825','832')
		--AND RV_COD = '701'
		AND SRV.D_E_L_E_T_ = '' 
WHERE RA_DEMISSA LIKE '2016%' 
	AND RA_CATFUNC = 'C'
	AND SRA.D_E_L_E_T_ = ''
GROUP BY RA_MAT, RA_NOME, RA_DEMISSA, RA_DESFUNC, RCC43.RCC_CONTEU, RD_PD, RD_VALOR, RA_TPCONTR, RCC37.RCC_CONTEU
ORDER BY RA_MAT

SELECT SUBSTRING(RCC_CONTEU,1,1) CONTRATO, SUBSTRING(RCC_CONTEU,3,4) EMPRESA, SUBSTRING(RCC_CONTEU,12,4) ACTRAB, SUBSTRING(RCC_CONTEU,28,3) FGTS, SUBSTRING(RCC_CONTEU,7,3) TERCEIROS ,* FROM RCC090 RCC WHERE RCC_CODIGO IN ('S037')  AND RCC.D_E_L_E_T_ = '' --AND RCC_CHAVE LIKE '2017%'


SELECT * FROM RCC090 RCC WHERE RCC_CODIGO = 'S037' AND RCC.D_E_L_E_T_ = ''
