SELECT RA_MAT, RA_NOME, RA_DEMISSA, RA_DESFUNC, SUBSTRING(RCC43.RCC_CONTEU,1,2) AS CODIGO, SUBSTRING(RCC43.RCC_CONTEU,3,30) AS DESCR, RR_PD, RV_DESC, RR_VALOR, RA_TPCONTR,
Convert(Numeric(10,2),SUBSTRING(RCC37.RCC_CONTEU,3,4)) AS EMPRESA,  Convert(Numeric(10,2),SUBSTRING(RCC37.RCC_CONTEU,12,4)) as ACTRAB, convert(numeric(10,2),SUBSTRING(RCC37.RCC_CONTEU,28,3)) as FGTS, (select convert(numeric(10,2),SUBSTRING(RCC38.RCC_CONTEU,7,3)) FROM RCC090 RCC38 WHERE RCC38.RCC_CODIGO = 'S038' AND RCC38.D_E_L_E_T_ = '') TERCEIROS
FROM SRR090 SRR 
	INNER JOIN SRA090 SRA ON SRA.RA_MAT = SRR.RR_MAT AND RA_CATFUNC = 'C' AND SRA.D_E_L_E_T_ = ''
	INNER JOIN SRG090 SRG ON SRG.RG_MAT = SRR.RR_MAT AND SRG.D_E_L_E_T_ = '' 
	INNER JOIN RCC090 RCC43 ON SUBSTRING(RCC43.RCC_CONTEU,1,2) = SRG.RG_TIPORES AND RCC_CODIGO = 'S043' AND RCC43.D_E_L_E_T_ = ''
	INNER JOIN RCC090 RCC37 ON SUBSTRING(RCC37.RCC_CONTEU,1,1) = RA_TPCONTR AND RCC37.RCC_CODIGO = 'S037' AND RCC37.D_E_L_E_T_ = ''
	INNER JOIN SRD090 SRD ON SRD.RD_MAT = SRA.RA_MAT AND SRD.D_E_L_E_T_ = '' 
	INNER JOIN SRV090 SRV ON SRV.RV_COD = SRR.RR_PD 
	--AND RV_COD IN ('701','702','703','825','832') 
	AND SRV.D_E_L_E_T_ = '' 
WHERE RR_TIPO3 = 'R'
	AND RR_DATA LIKE '2016%'
	AND SRR.RR_PD IN ('701','702','703','825','832')  
	AND SRR.D_E_L_E_T_ = '' 
GROUP BY RA_MAT, RA_NOME, RA_DEMISSA, RA_DESFUNC, RCC43.RCC_CONTEU, RR_PD, RR_VALOR, RA_TPCONTR, RCC37.RCC_CONTEU, RV_DESC
ORDER BY RA_NOME

--VERSAO 02 
SELECT RA_MAT, RA_NOME, RA_DEMISSA, RA_DESFUNC, SUBSTRING(RCC_CONTEU,1,2) AS CODIGO, SUBSTRING(RCC_CONTEU,3,30) AS DESCR, RD_PD, RD_VALOR
FROM SRA090 SRA
	INNER JOIN SRG090 SRG ON SRG.RG_MAT = RA_MAT 
		AND SRG.D_E_L_E_T_ = ''
	INNER JOIN RCC090 RCC ON SUBSTRING(RCC.RCC_CONTEU,1,2) = SRG.RG_TIPORES 
		AND RCC_CODIGO = 'S043'
		AND  SUBSTRING(RCC_CONTEU,1,2) = '20'
		AND RCC.D_E_L_E_T_ = ''
	INNER JOIN SRD090 SRD ON SRD.RD_MAT = SRA.RA_MAT
		AND SRD.D_E_L_E_T_ = ''	AND RD_TIPO2 = 'R'
	INNER JOIN SRV090 SRV ON SRV.RV_COD = SRD.RD_PD
		--AND RV_COD IN ('701','702','703','825','832')
		AND RV_COD = '701'
		AND SRV.D_E_L_E_T_ = '' 
WHERE RA_DEMISSA LIKE '2016%' 
	AND RA_CATFUNC = 'C'
	AND SRA.D_E_L_E_T_ = ''
GROUP BY RA_MAT, RA_NOME, RA_DEMISSA, RA_DESFUNC, RCC_CONTEU, RD_PD, RD_VALOR
ORDER BY RA_MAT


-- versao 03

SELECT RA_MAT, RA_NOME, RA_DEMISSA, RA_DESFUNC, SUBSTRING(RCC43.RCC_CONTEU,1,2) AS CODIGO, SUBSTRING(RCC43.RCC_CONTEU,3,30) AS DESCR, RD_PD, RD_VALOR, RA_TPCONTR,
SUBSTRING(RCC37.RCC_CONTEU,3,4) EMPRESA, SUBSTRING(RCC37.RCC_CONTEU,12,4) ACTRAB, SUBSTRING(RCC37.RCC_CONTEU,28,3) FGTS
FROM SRA090 SRA
	INNER JOIN SRG090 SRG ON SRG.RG_MAT = RA_MAT 
		AND SRG.D_E_L_E_T_ = ''
	INNER JOIN RCC090 RCC43 ON SUBSTRING(RCC43.RCC_CONTEU,1,2) = SRG.RG_TIPORES
		AND RCC_CODIGO = 'S043'
		AND RCC43.D_E_L_E_T_ = ''
	LEFT JOIN RCC090 RCC37 ON SUBSTRING(RCC37.RCC_CONTEU,1,1) = RA_TPCONTR
		AND RCC37.RCC_CODIGO = 'S037'
		AND RCC37.D_E_L_E_T_ = ''
	INNER JOIN SRD090 SRD ON SRD.RD_MAT = SRA.RA_MAT
		AND SRD.D_E_L_E_T_ = ''	AND RD_TIPO2 = 'R'
	INNER JOIN SRV090 SRV ON SRV.RV_COD = SRD.RD_PD
		AND RV_COD IN ('701','702','703','825','832')
		--AND RV_COD = '701'
		AND SRV.D_E_L_E_T_ = '' 
WHERE RA_DEMISSA LIKE '2016%' 
	AND RA_CATFUNC = 'C'
	AND SRA.D_E_L_E_T_ = ''
GROUP BY RA_MAT, RA_NOME, RA_DEMISSA, RA_DESFUNC, RCC43.RCC_CONTEU, RD_PD, RD_VALOR, RA_TPCONTR, RCC37.RCC_CONTEU
ORDER BY RA_MAT

SELECT SUBSTRING(RCC_CONTEU,1,1) CONTRATO, SUBSTRING(RCC_CONTEU,3,4) EMPRESA, SUBSTRING(RCC_CONTEU,12,4) ACTRAB, SUBSTRING(RCC_CONTEU,28,3) FGTS, SUBSTRING(RCC_CONTEU,7,3) TERCEIROS ,* FROM RCC090 RCC WHERE RCC_CODIGO IN ('S037')  AND RCC.D_E_L_E_T_ = '' --AND RCC_CHAVE LIKE '2017%'


SELECT * FROM RCC090 RCC WHERE RCC_CODIGO = 'S037' AND RCC.D_E_L_E_T_ = ''

-- versao 04

SELECT RA_MAT, RA_NOME, RA_DEMISSA, RA_DESFUNC, SUBSTRING(RCC43.RCC_CONTEU,1,2) AS CODIGO, SUBSTRING(RCC43.RCC_CONTEU,3,30) AS DESCR, RD_PD, RD_VALOR, RA_TPCONTR,
Convert(Numeric(10,2),SUBSTRING(RCC37.RCC_CONTEU,3,4)) AS EMPRESA,  Convert(Numeric(10,2),SUBSTRING(RCC37.RCC_CONTEU,12,4)) as ACTRAB, convert(numeric(10,2),SUBSTRING(RCC37.RCC_CONTEU,28,3)) as FGTS, (select convert(numeric(10,2),SUBSTRING(RCC38.RCC_CONTEU,7,3)) FROM RCC090 RCC38 WHERE RCC38.RCC_CODIGO = 'S038' AND RCC38.D_E_L_E_T_ = '') TERCEIROS
FROM SRA090 SRA
	INNER JOIN SRG090 SRG ON SRG.RG_MAT = RA_MAT 
		AND SRG.D_E_L_E_T_ = ''
	INNER JOIN RCC090 RCC43 ON SUBSTRING(RCC43.RCC_CONTEU,1,2) = SRG.RG_TIPORES
		AND RCC_CODIGO = 'S043'
		AND RCC43.D_E_L_E_T_ = ''
	LEFT JOIN RCC090 RCC37 ON SUBSTRING(RCC37.RCC_CONTEU,1,1) = RA_TPCONTR
		AND RCC37.RCC_CODIGO = 'S037'
		AND RCC37.D_E_L_E_T_ = ''	
	INNER JOIN SRD090 SRD ON SRD.RD_MAT = SRA.RA_MAT
		AND SRD.D_E_L_E_T_ = ''	AND RD_TIPO2 = 'R'
	INNER JOIN SRV090 SRV ON SRV.RV_COD = SRD.RD_PD
		AND RV_COD IN ('701','702','703','825','832')
		AND SRV.D_E_L_E_T_ = '' 
WHERE RA_DEMISSA LIKE '2016%' 
	AND RA_CATFUNC = 'C'
	AND SRA.D_E_L_E_T_ = ''
GROUP BY RA_MAT, RA_NOME, RA_DEMISSA, RA_DESFUNC, RCC43.RCC_CONTEU, RD_PD, RD_VALOR, RA_TPCONTR, RCC37.RCC_CONTEU
ORDER BY RA_MAT

SELECT SUBSTRING(RCC_CONTEU,1,1) CONTRATO, SUBSTRING(RCC_CONTEU,3,4) EMPRESA, SUBSTRING(RCC_CONTEU,12,4) ACTRAB, SUBSTRING(RCC_CONTEU,28,3) FGTS, SUBSTRING(RCC_CONTEU,7,3) TERCEIROS ,* FROM RCC090 RCC WHERE RCC_CODIGO IN ('S037')  AND RCC.D_E_L_E_T_ = '' --AND RCC_CHAVE LIKE '2017%'

SELECT RR_PD, RV_DESC ,* FROM SRR090 SRR 
INNER JOIN SRV090 SRV ON RV_COD = RR_PD AND SRV.D_E_L_E_T_ = ''
WHERE RR_TIPO3 = 'R' AND SRR.D_E_L_E_T_ = '' AND RR_DATA LIKE '2016%' AND RR_PD IN ('701','702','703','825','832', '751', '778', '843')


