-- CRIAR UMA VIEW DA TABELA CT2 NO SQL SERVER

CREATE VIEW VW_CT2100 AS (

-- COMANDO SELECT ...  )

  
  -- ALTERANDO VIEW
  
  USE [db_mp12_h]
GO

/****** Object:  View [dbo].[VW_CT2100]    Script Date: 23/07/2018 17:04:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_CT2100] AS (

SELECT 'PREVIDENCIAL' AS EMPRESA, CT2_FILIAL, CONVERT(DATE,CT2_DATA,105) AS CT2_DATA, CT2_LOTE,
CASE CT2_DC 
	WHEN '1' THEN 'DEBITO'
	WHEN '2' THEN 'CREDITO' 
	WHEN '3' THEN 'PARTIDA DOBRADA'
	WHEN '4' THEN 'CONT. HIST'
	WHEN '5' THEN 'RATEIO'
	WHEN '6' THEN 'LANCAMENTO PADRAO' END AS CT2_DC, CT2_DEBITO, CT2_CREDIT, CT1DEB.CT1_DESC01 AS DESCR_DEB, CT1CRE.CT1_DESC01 AS DESCR_CRED, 
	CT2_VALOR, CT2_HIST, CT2_CCD, 
	
	(CASE CT2_DC WHEN '3' THEN '' ELSE CT2_CCC END) CT2_CCC,
	
	CTTDEB.CTT_DESC01 AS DESC_DEB, CTTCRE.CTT_DESC01 AS DESC_CRED, CT2_CLVLDB, CT2_CLVLCR, CTHDEB.CTH_DESC01 AS DES_DEB, CTHCRE.CTH_DESC01 AS DES_CRED
FROM CT2100 CT2
	LEFT JOIN CT1100 CT1DEB ON CT2_DEBITO = CT1DEB.CT1_CONTA AND CT1DEB.D_E_L_E_T_ = '' 
	LEFT JOIN CT1100 CT1CRE ON CT2_CREDIT = CT1CRE.CT1_CONTA AND CT1CRE.D_E_L_E_T_ = ''
	LEFT JOIN CTT100 CTTDEB ON CT2_CCD = CTTDEB.CTT_CUSTO AND CTTDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTT100 CTTCRE ON CT2_CCC = CTTCRE.CTT_CUSTO AND CTTCRE.D_E_L_E_T_ = ''
	LEFT JOIN CTH100 CTHDEB ON CT2_CLVLDB = CTHDEB.CTH_CLVL AND CTHDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTH100 CTHCRE ON CT2_CLVLCR = CTHCRE.CTH_CLVL AND CTHCRE.D_E_L_E_T_ = ''
WHERE CT2.D_E_L_E_T_ = ''
	AND CT2_HIST <> 'ENCERRAMENTO DO EXERCICIO'
)
GO




