USE [db_mp12_h]
GO

/****** Object:  View [dbo].[VW_CT2100]    Script Date: 12/11/2018 13:38:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[VW_CT2100] AS (

SELECT 'EMPRESA_01' AS EMPRESA, CT2_FILIAL, CONVERT(DATE,CT2_DATA,105) AS CT2_DATA, CT2_LOTE,
CASE CT2_DC 
	WHEN '1' THEN 'DEBITO'
	WHEN '2' THEN 'CREDITO' 
	WHEN '3' THEN 'PARTIDA DOBRADA'
	WHEN '4' THEN 'CONT. HIST'
	WHEN '5' THEN 'RATEIO'
	WHEN '6' THEN 'LANCAMENTO PADRAO' END AS CT2_DC, CT2_DEBITO, CT2_CREDIT, CT1DEB.CT1_DESC01 AS DESCR_DEB, CT1CRE.CT1_DESC01 AS DESCR_CRED, 
	CT2_VALOR, CT2_HIST, CT2_CCC,	
	(CASE CT2_DC WHEN '3' THEN '' ELSE CT2_CCD END) CT2_CCD,	
	CTTDEB.CTT_DESC01 AS DESC_DEB, CTTCRE.CTT_DESC01 AS DESC_CRED, CT2_CLVLDB, CT2_CLVLCR, CTHDEB.CTH_DESC01 AS DES_DEB, CTHCRE.CTH_DESC01 AS DES_CRED
FROM CT2010 CT2
	LEFT JOIN CT1030 CT1DEB ON CT2_DEBITO = CT1DEB.CT1_CONTA AND CT1DEB.D_E_L_E_T_ = '' 
	LEFT JOIN CT1030 CT1CRE ON CT2_CREDIT = CT1CRE.CT1_CONTA AND CT1CRE.D_E_L_E_T_ = ''
	LEFT JOIN CTT010 CTTDEB ON CT2_CCD = CTTDEB.CTT_CUSTO AND CT2.CT2_FILIAL = CTTDEB.CTT_FILIAL AND CTTDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTT010 CTTCRE ON CT2_CCC = CTTCRE.CTT_CUSTO AND CT2.CT2_FILIAL = CTTCRE.CTT_FILIAL AND CTTCRE.D_E_L_E_T_ = ''
	LEFT JOIN CTH010 CTHDEB ON CT2_CLVLDB = CTHDEB.CTH_CLVL AND CT2.CT2_FILIAL = CTHDEB.CTH_FILIAL AND CTHDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTH010 CTHCRE ON CT2_CLVLCR = CTHCRE.CTH_CLVL AND CT2.CT2_FILIAL = CTHCRE.CTH_FILIAL AND CTHCRE.D_E_L_E_T_ = ''
WHERE CT2.D_E_L_E_T_ = ''
	AND CT2_HIST <> 'ENCERRAMENTO DO EXERCICIO'
	AND CT2.CT2_FILIAL = '01'
UNION ALL
SELECT 'EMPRESA_02' AS EMPRESA, CT2_FILIAL, CONVERT(DATE,CT2_DATA,105) AS CT2_DATA, CT2_LOTE,
CASE CT2_DC 
	WHEN '1' THEN 'DEBITO'
	WHEN '2' THEN 'CREDITO' 
	WHEN '3' THEN 'PARTIDA DOBRADA'
	WHEN '4' THEN 'CONT. HIST'
	WHEN '5' THEN 'RATEIO'
	WHEN '6' THEN 'LANCAMENTO PADRAO' END AS CT2_DC, CT2_DEBITO, CT2_CREDIT, CT1DEB.CT1_DESC01 AS DESCR_DEB, CT1CRE.CT1_DESC01 AS DESCR_CRED, 
	CT2_VALOR, CT2_HIST, CT2_CCC,	
	(CASE CT2_DC WHEN '3' THEN '' ELSE CT2_CCD END) CT2_CCD,	
	CTTDEB.CTT_DESC01 AS DESC_DEB, CTTCRE.CTT_DESC01 AS DESC_CRED, CT2_CLVLDB, CT2_CLVLCR, CTHDEB.CTH_DESC01 AS DES_DEB, CTHCRE.CTH_DESC01 AS DES_CRED
FROM CT2010 CT2
	LEFT JOIN CT1030 CT1DEB ON CT2_DEBITO = CT1DEB.CT1_CONTA AND CT1DEB.D_E_L_E_T_ = '' 
	LEFT JOIN CT1030 CT1CRE ON CT2_CREDIT = CT1CRE.CT1_CONTA AND CT1CRE.D_E_L_E_T_ = ''
	LEFT JOIN CTT010 CTTDEB ON CT2_CCD = CTTDEB.CTT_CUSTO AND CT2.CT2_FILIAL = CTTDEB.CTT_FILIAL AND CTTDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTT010 CTTCRE ON CT2_CCC = CTTCRE.CTT_CUSTO AND CT2.CT2_FILIAL = CTTCRE.CTT_FILIAL AND CTTCRE.D_E_L_E_T_ = ''
	LEFT JOIN CTH010 CTHDEB ON CT2_CLVLDB = CTHDEB.CTH_CLVL AND CT2.CT2_FILIAL = CTHDEB.CTH_FILIAL AND CTHDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTH010 CTHCRE ON CT2_CLVLCR = CTHCRE.CTH_CLVL AND CT2.CT2_FILIAL = CTHCRE.CTH_FILIAL AND CTHCRE.D_E_L_E_T_ = ''
WHERE CT2.D_E_L_E_T_ = ''
	AND CT2_HIST <> 'ENCERRAMENTO DO EXERCICIO'
	AND CT2.CT2_FILIAL = '02'
UNION ALL
SELECT 'EMPRESA_03' AS EMPRESA, CT2_FILIAL, CONVERT(DATE,CT2_DATA,105) AS CT2_DATA, CT2_LOTE,
CASE CT2_DC 
	WHEN '1' THEN 'DEBITO'
	WHEN '2' THEN 'CREDITO' 
	WHEN '3' THEN 'PARTIDA DOBRADA'
	WHEN '4' THEN 'CONT. HIST'
	WHEN '5' THEN 'RATEIO'
	WHEN '6' THEN 'LANCAMENTO PADRAO' END AS CT2_DC, CT2_DEBITO, CT2_CREDIT, CT1DEB.CT1_DESC01 AS DESCR_DEB, CT1CRE.CT1_DESC01 AS DESCR_CRED, 
	CT2_VALOR, CT2_HIST, CT2_CCC,	
	(CASE CT2_DC WHEN '3' THEN '' ELSE CT2_CCD END) CT2_CCD,	
	CTTDEB.CTT_DESC01 AS DESC_DEB, CTTCRE.CTT_DESC01 AS DESC_CRED, CT2_CLVLDB, CT2_CLVLCR, CTHDEB.CTH_DESC01 AS DES_DEB, CTHCRE.CTH_DESC01 AS DES_CRED
FROM CT2030 CT2
	LEFT JOIN CT1030 CT1DEB ON CT2_DEBITO = CT1DEB.CT1_CONTA AND CT1DEB.D_E_L_E_T_ = '' 
	LEFT JOIN CT1030 CT1CRE ON CT2_CREDIT = CT1CRE.CT1_CONTA AND CT1CRE.D_E_L_E_T_ = ''
	LEFT JOIN CTT030 CTTDEB ON CT2_CCD = CTTDEB.CTT_CUSTO AND CT2.CT2_FILIAL = CTTDEB.CTT_FILIAL AND CTTDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTT030 CTTCRE ON CT2_CCC = CTTCRE.CTT_CUSTO AND CT2.CT2_FILIAL = CTTCRE.CTT_FILIAL AND CTTCRE.D_E_L_E_T_ = ''
	LEFT JOIN CTH030 CTHDEB ON CT2_CLVLDB = CTHDEB.CTH_CLVL AND CT2.CT2_FILIAL = CTHDEB.CTH_FILIAL AND CTHDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTH030 CTHCRE ON CT2_CLVLCR = CTHCRE.CTH_CLVL AND CT2.CT2_FILIAL = CTHCRE.CTH_FILIAL AND CTHCRE.D_E_L_E_T_ = ''
WHERE CT2.D_E_L_E_T_ = ''
	AND CT2_HIST <> 'ENCERRAMENTO DO EXERCICIO'
UNION ALL
SELECT 'EMPRESA_04' AS EMPRESA, CT2_FILIAL, CONVERT(DATE,CT2_DATA,105) AS CT2_DATA, CT2_LOTE,
CASE CT2_DC 
	WHEN '1' THEN 'DEBITO'
	WHEN '2' THEN 'CREDITO' 
	WHEN '3' THEN 'PARTIDA DOBRADA'
	WHEN '4' THEN 'CONT. HIST'
	WHEN '5' THEN 'RATEIO'
	WHEN '6' THEN 'LANCAMENTO PADRAO' END AS CT2_DC, CT2_DEBITO, CT2_CREDIT, CT1DEB.CT1_DESC01 AS DESCR_DEB, CT1CRE.CT1_DESC01 AS DESCR_CRED, 
	CT2_VALOR, CT2_HIST, CT2_CCC,	
	(CASE CT2_DC WHEN '3' THEN '' ELSE CT2_CCD END) CT2_CCD,	
	CTTDEB.CTT_DESC01 AS DESC_DEB, CTTCRE.CTT_DESC01 AS DESC_CRED, CT2_CLVLDB, CT2_CLVLCR, CTHDEB.CTH_DESC01 AS DES_DEB, CTHCRE.CTH_DESC01 AS DES_CRED
FROM CT2040 CT2
	LEFT JOIN CT1030 CT1DEB ON CT2_DEBITO = CT1DEB.CT1_CONTA AND CT1DEB.D_E_L_E_T_ = '' 
	LEFT JOIN CT1030 CT1CRE ON CT2_CREDIT = CT1CRE.CT1_CONTA AND CT1CRE.D_E_L_E_T_ = ''
	LEFT JOIN CTT040 CTTDEB ON CT2_CCD = CTTDEB.CTT_CUSTO AND CT2.CT2_FILIAL = CTTDEB.CTT_FILIAL AND CTTDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTT040 CTTCRE ON CT2_CCC = CTTCRE.CTT_CUSTO AND CT2.CT2_FILIAL = CTTCRE.CTT_FILIAL AND CTTCRE.D_E_L_E_T_ = ''
	LEFT JOIN CTH040 CTHDEB ON CT2_CLVLDB = CTHDEB.CTH_CLVL AND CT2.CT2_FILIAL = CTHDEB.CTH_FILIAL AND CTHDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTH040 CTHCRE ON CT2_CLVLCR = CTHCRE.CTH_CLVL AND CT2.CT2_FILIAL = CTHCRE.CTH_FILIAL AND CTHCRE.D_E_L_E_T_ = ''
WHERE CT2.D_E_L_E_T_ = ''
	AND CT2_HIST <> 'ENCERRAMENTO DO EXERCICIO'
UNION ALL
SELECT 'EMPRESA_05' AS EMPRESA, CT2_FILIAL, CONVERT(DATE,CT2_DATA,105) AS CT2_DATA, CT2_LOTE,
CASE CT2_DC 
	WHEN '1' THEN 'DEBITO'
	WHEN '2' THEN 'CREDITO' 
	WHEN '3' THEN 'PARTIDA DOBRADA'
	WHEN '4' THEN 'CONT. HIST'
	WHEN '5' THEN 'RATEIO'
	WHEN '6' THEN 'LANCAMENTO PADRAO' END AS CT2_DC, CT2_DEBITO, CT2_CREDIT, CT1DEB.CT1_DESC01 AS DESCR_DEB, CT1CRE.CT1_DESC01 AS DESCR_CRED, 
	CT2_VALOR, CT2_HIST, CT2_CCC,	
	(CASE CT2_DC WHEN '3' THEN '' ELSE CT2_CCD END) CT2_CCD,	
	CTTDEB.CTT_DESC01 AS DESC_DEB, CTTCRE.CTT_DESC01 AS DESC_CRED, CT2_CLVLDB, CT2_CLVLCR, CTHDEB.CTH_DESC01 AS DES_DEB, CTHCRE.CTH_DESC01 AS DES_CRED
FROM CT2060 CT2
	LEFT JOIN CT1030 CT1DEB ON CT2_DEBITO = CT1DEB.CT1_CONTA AND CT1DEB.D_E_L_E_T_ = '' 
	LEFT JOIN CT1030 CT1CRE ON CT2_CREDIT = CT1CRE.CT1_CONTA AND CT1CRE.D_E_L_E_T_ = ''
	LEFT JOIN CTT060 CTTDEB ON CT2_CCD = CTTDEB.CTT_CUSTO AND CT2.CT2_FILIAL = CTTDEB.CTT_FILIAL AND CTTDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTT060 CTTCRE ON CT2_CCC = CTTCRE.CTT_CUSTO AND CT2.CT2_FILIAL = CTTCRE.CTT_FILIAL AND CTTCRE.D_E_L_E_T_ = ''
	LEFT JOIN CTH060 CTHDEB ON CT2_CLVLDB = CTHDEB.CTH_CLVL AND CT2.CT2_FILIAL = CTHDEB.CTH_FILIAL AND CTHDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTH060 CTHCRE ON CT2_CLVLCR = CTHCRE.CTH_CLVL AND CT2.CT2_FILIAL = CTHCRE.CTH_FILIAL AND CTHCRE.D_E_L_E_T_ = ''
WHERE CT2.D_E_L_E_T_ = ''
	AND CT2_HIST <> 'ENCERRAMENTO DO EXERCICIO'
UNION ALL
SELECT 'EMPRESA_06' AS EMPRESA, CT2_FILIAL, CONVERT(DATE,CT2_DATA,105) AS CT2_DATA, CT2_LOTE,
CASE CT2_DC 
	WHEN '1' THEN 'DEBITO'
	WHEN '2' THEN 'CREDITO' 
	WHEN '3' THEN 'PARTIDA DOBRADA'
	WHEN '4' THEN 'CONT. HIST'
	WHEN '5' THEN 'RATEIO'
	WHEN '6' THEN 'LANCAMENTO PADRAO' END AS CT2_DC, CT2_DEBITO, CT2_CREDIT, CT1DEB.CT1_DESC01 AS DESCR_DEB, CT1CRE.CT1_DESC01 AS DESCR_CRED, 
	CT2_VALOR, CT2_HIST, CT2_CCC,	
	(CASE CT2_DC WHEN '3' THEN '' ELSE CT2_CCD END) CT2_CCD,	
	CTTDEB.CTT_DESC01 AS DESC_DEB, CTTCRE.CTT_DESC01 AS DESC_CRED, CT2_CLVLDB, CT2_CLVLCR, CTHDEB.CTH_DESC01 AS DES_DEB, CTHCRE.CTH_DESC01 AS DES_CRED
FROM CT2070 CT2
	LEFT JOIN CT1030 CT1DEB ON CT2_DEBITO = CT1DEB.CT1_CONTA AND CT1DEB.D_E_L_E_T_ = '' 
	LEFT JOIN CT1030 CT1CRE ON CT2_CREDIT = CT1CRE.CT1_CONTA AND CT1CRE.D_E_L_E_T_ = ''
	LEFT JOIN CTT070 CTTDEB ON CT2_CCD = CTTDEB.CTT_CUSTO AND CT2.CT2_FILIAL = CTTDEB.CTT_FILIAL AND CTTDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTT070 CTTCRE ON CT2_CCC = CTTCRE.CTT_CUSTO AND CT2.CT2_FILIAL = CTTCRE.CTT_FILIAL AND CTTCRE.D_E_L_E_T_ = ''
	LEFT JOIN CTH070 CTHDEB ON CT2_CLVLDB = CTHDEB.CTH_CLVL AND CT2.CT2_FILIAL = CTHDEB.CTH_FILIAL AND CTHDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTH070 CTHCRE ON CT2_CLVLCR = CTHCRE.CTH_CLVL AND CT2.CT2_FILIAL = CTHCRE.CTH_FILIAL AND CTHCRE.D_E_L_E_T_ = ''
WHERE CT2.D_E_L_E_T_ = ''
	AND CT2_HIST <> 'ENCERRAMENTO DO EXERCICIO'
UNION ALL
SELECT 'EMPRESA_07' AS EMPRESA, CT2_FILIAL, CONVERT(DATE,CT2_DATA,105) AS CT2_DATA, CT2_LOTE,
CASE CT2_DC 
	WHEN '1' THEN 'DEBITO'
	WHEN '2' THEN 'CREDITO' 
	WHEN '3' THEN 'PARTIDA DOBRADA'
	WHEN '4' THEN 'CONT. HIST'
	WHEN '5' THEN 'RATEIO'
	WHEN '6' THEN 'LANCAMENTO PADRAO' END AS CT2_DC, CT2_DEBITO, CT2_CREDIT, CT1DEB.CT1_DESC01 AS DESCR_DEB, CT1CRE.CT1_DESC01 AS DESCR_CRED, 
	CT2_VALOR, CT2_HIST, CT2_CCC,	
	(CASE CT2_DC WHEN '3' THEN '' ELSE CT2_CCD END) CT2_CCD,	
	CTTDEB.CTT_DESC01 AS DESC_DEB, CTTCRE.CTT_DESC01 AS DESC_CRED, CT2_CLVLDB, CT2_CLVLCR, CTHDEB.CTH_DESC01 AS DES_DEB, CTHCRE.CTH_DESC01 AS DES_CRED
FROM CT2090 CT2
	LEFT JOIN CT1030 CT1DEB ON CT2_DEBITO = CT1DEB.CT1_CONTA AND CT1DEB.D_E_L_E_T_ = '' 
	LEFT JOIN CT1030 CT1CRE ON CT2_CREDIT = CT1CRE.CT1_CONTA AND CT1CRE.D_E_L_E_T_ = ''
	LEFT JOIN CTT090 CTTDEB ON CT2_CCD = CTTDEB.CTT_CUSTO AND CT2.CT2_FILIAL = CTTDEB.CTT_FILIAL AND CTTDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTT090 CTTCRE ON CT2_CCC = CTTCRE.CTT_CUSTO AND CT2.CT2_FILIAL = CTTCRE.CTT_FILIAL AND CTTCRE.D_E_L_E_T_ = ''
	LEFT JOIN CTH090 CTHDEB ON CT2_CLVLDB = CTHDEB.CTH_CLVL AND CT2.CT2_FILIAL = CTHDEB.CTH_FILIAL AND CTHDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTH090 CTHCRE ON CT2_CLVLCR = CTHCRE.CTH_CLVL AND CT2.CT2_FILIAL = CTHCRE.CTH_FILIAL AND CTHCRE.D_E_L_E_T_ = ''
WHERE CT2.D_E_L_E_T_ = ''
	AND CT2_HIST <> 'ENCERRAMENTO DO EXERCICIO'
UNION ALL
SELECT 'EMPRESA_08' AS EMPRESA, CT2_FILIAL, CONVERT(DATE,CT2_DATA,105) AS CT2_DATA, CT2_LOTE,
CASE CT2_DC 
	WHEN '1' THEN 'DEBITO'
	WHEN '2' THEN 'CREDITO' 
	WHEN '3' THEN 'PARTIDA DOBRADA'
	WHEN '4' THEN 'CONT. HIST'
	WHEN '5' THEN 'RATEIO'
	WHEN '6' THEN 'LANCAMENTO PADRAO' END AS CT2_DC, CT2_DEBITO, CT2_CREDIT, CT1DEB.CT1_DESC01 AS DESCR_DEB, CT1CRE.CT1_DESC01 AS DESCR_CRED, 
	CT2_VALOR, CT2_HIST, CT2_CCC,	
	(CASE CT2_DC WHEN '3' THEN '' ELSE CT2_CCD END) CT2_CCD,	
	CTTDEB.CTT_DESC01 AS DESC_DEB, CTTCRE.CTT_DESC01 AS DESC_CRED, CT2_CLVLDB, CT2_CLVLCR, CTHDEB.CTH_DESC01 AS DES_DEB, CTHCRE.CTH_DESC01 AS DES_CRED
FROM CT2100 CT2
	LEFT JOIN CT1100 CT1DEB ON CT2_DEBITO = CT1DEB.CT1_CONTA AND CT1DEB.D_E_L_E_T_ = '' 
	LEFT JOIN CT1100 CT1CRE ON CT2_CREDIT = CT1CRE.CT1_CONTA AND CT1CRE.D_E_L_E_T_ = ''
	LEFT JOIN CTT100 CTTDEB ON CT2_CCD = CTTDEB.CTT_CUSTO AND CT2.CT2_FILIAL = CTTDEB.CTT_FILIAL AND CTTDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTT100 CTTCRE ON CT2_CCC = CTTCRE.CTT_CUSTO AND CT2.CT2_FILIAL = CTTCRE.CTT_FILIAL AND CTTCRE.D_E_L_E_T_ = ''
	LEFT JOIN CTH100 CTHDEB ON CT2_CLVLDB = CTHDEB.CTH_CLVL AND CT2.CT2_FILIAL = CTHDEB.CTH_FILIAL AND CTHDEB.D_E_L_E_T_ = ''
	LEFT JOIN CTH100 CTHCRE ON CT2_CLVLCR = CTHCRE.CTH_CLVL AND CT2.CT2_FILIAL = CTHCRE.CTH_FILIAL AND CTHCRE.D_E_L_E_T_ = ''
WHERE CT2.D_E_L_E_T_ = ''
	AND CT2_HIST <> 'ENCERRAMENTO DO EXERCICIO'
)
GO
